"""Python idiom/recipe skills — how to *structure* real Python, not just call an API.

Compact specs; the forge renders each into an immense standalone SKILL.md. These
cover the language patterns an agent needs to write idiomatic, correct Python.
"""
from __future__ import annotations


def _r(title, desc, intro, examples, pitfalls, related):
    return {"title": title, "desc": desc, "intro": intro,
            "examples": examples, "pitfalls": pitfalls, "related": related}


PY_RECIPES = {
    "comprehensions": _r(
        "List / dict / set comprehensions",
        "Build lists, dicts, and sets declaratively with comprehensions instead of manual loops and appends.",
        "A comprehension expresses 'transform and filter this iterable into a new collection' in one readable expression. It is faster than an append loop and signals intent.",
        [("List", "squares = [n * n for n in range(10)]\nevens = [n for n in nums if n % 2 == 0]"),
         ("Dict", "by_id = {u.id: u for u in users}\nlengths = {w: len(w) for w in words}"),
         ("Set", "unique_domains = {email.split('@')[1] for email in emails}"),
         ("Nested", "flat = [x for row in matrix for x in row]")],
        ["Do not build a comprehension for its side effects — use a plain for loop when you are not collecting a result.",
         "Deeply nested comprehensions hurt readability; switch to a loop or generator past two clauses."],
        ["generators", "enumerate-zip", "map-filter"]),
    "generators": _r(
        "Generators and lazy iteration",
        "Produce values lazily with yield so you can stream large or infinite sequences without holding them in memory.",
        "A generator function uses `yield` to produce a stream of values on demand. It keeps memory flat regardless of how much data flows through, which is essential for large files and pipelines.",
        [("Generator function", "def read_chunks(f, size=4096):\n    while chunk := f.read(size):\n        yield chunk"),
         ("Generator expression", "total = sum(len(line) for line in open('big.txt'))"),
         ("Pipeline", "lines = (l.strip() for l in f)\nnonempty = (l for l in lines if l)\nfor l in nonempty:\n    handle(l)")],
        ["A generator is single-use: once exhausted, iterating again yields nothing.",
         "Do not call len() on a generator; materialize with list() only when you truly need all of it."],
        ["comprehensions", "python-itertools", "iterators"]),
    "context-managers": _r(
        "Context managers (`with`)",
        "Acquire and release resources safely using with-statements and custom context managers so cleanup always runs.",
        "The `with` statement guarantees teardown (close, unlock, restore) even when the body raises. Write your own with `contextlib.contextmanager` or `__enter__`/`__exit__`.",
        [("Files", "with open('f.txt') as f:\n    data = f.read()\n# f is closed here, even on error"),
         ("Multiple", "with open('a') as a, open('b', 'w') as b:\n    b.write(a.read())"),
         ("Custom", "from contextlib import contextmanager\n\n@contextmanager\ndef timer():\n    import time; t = time.perf_counter()\n    try:\n        yield\n    finally:\n        print(time.perf_counter() - t)")],
        ["Do not manually call close() when a with-block can do it for you.",
         "In a @contextmanager, put teardown in a finally so it runs even if the body raises."],
        ["exception-handling", "python-contextlib"]),
    "dataclasses": _r(
        "Dataclasses",
        "Model plain data with @dataclass to get init, repr, and comparison for free instead of boilerplate classes.",
        "`@dataclass` generates `__init__`, `__repr__`, and `__eq__` from typed fields. Use it for records and value objects; it is the modern default over hand-written classes or bare tuples.",
        [("Basic", "from dataclasses import dataclass\n\n@dataclass\nclass Point:\n    x: float\n    y: float = 0.0"),
         ("Frozen (hashable)", "@dataclass(frozen=True)\nclass Config:\n    host: str\n    port: int = 8080"),
         ("Defaults that are mutable", "from dataclasses import field\n\n@dataclass\nclass Bag:\n    items: list = field(default_factory=list)")],
        ["Never use a mutable default directly (items: list = []); use field(default_factory=list).",
         "frozen=True makes instances immutable and hashable — but you cannot reassign fields."],
        ["namedtuple", "typing-hints", "enum"]),
    "enum": _r(
        "Enumerations (`enum`)",
        "Give a fixed set of related constants real names and type-safety with the enum module.",
        "An `Enum` replaces magic strings/numbers with named, comparable, self-documenting members. Use it for states, modes, and categories.",
        [("Define", "from enum import Enum\n\nclass Color(Enum):\n    RED = 1\n    GREEN = 2\n    BLUE = 3"),
         ("Use", "c = Color.RED\nif c is Color.RED: ...\nprint(c.name, c.value)"),
         ("String enum", "from enum import StrEnum\n\nclass Env(StrEnum):\n    DEV = 'dev'\n    PROD = 'prod'")],
        ["Compare members with `is`, not `==` to string values.",
         "Members are singletons — don't instantiate the enum class to make one."],
        ["dataclasses", "match-statement"]),
    "f-strings": _r(
        "f-strings and formatting",
        "Interpolate and format values directly in string literals with f-strings, including alignment and precision.",
        "f-strings embed expressions in `{}` and support the full format mini-language: width, alignment, precision, and thousands separators. They are the clearest, fastest way to build strings.",
        [("Basic", "name = 'Ada'\nprint(f'Hello, {name}!')"),
         ("Format spec", "print(f'{price:>10.2f}')   # right-aligned, 2 decimals\nprint(f'{n:,}')            # thousands separator"),
         ("Debug (=)", "x = 42\nprint(f'{x=}')            # -> x=42")],
        ["Braces need doubling to be literal: f'{{not a field}}'.",
         "Keep heavy logic out of the braces — compute first, interpolate second."],
        ["string-formatting", "python-string"]),
    "unpacking": _r(
        "Tuple / iterable unpacking",
        "Destructure sequences and dicts into variables, including starred rest-capture, for clean assignments.",
        "Unpacking binds multiple names at once and captures the 'rest' with `*`. It makes swaps, multiple returns, and head/tail splits obvious.",
        [("Basic + swap", "a, b = 1, 2\na, b = b, a"),
         ("Starred", "first, *middle, last = [1, 2, 3, 4, 5]"),
         ("In loops / returns", "for key, value in d.items():\n    ...\n\ndef minmax(xs):\n    return min(xs), max(xs)\nlo, hi = minmax(data)"),
         ("Merge dicts", "merged = {**defaults, **overrides}")],
        ["Starred target captures a list, possibly empty — handle the empty case.",
         "The number of non-starred targets must match, or you get a ValueError."],
        ["star-args", "enumerate-zip"]),
    "star-args": _r(
        "*args and **kwargs",
        "Write functions that accept any number of positional and keyword arguments and forward them cleanly.",
        "`*args` collects extra positionals into a tuple; `**kwargs` collects extra keywords into a dict. Use them for wrappers, decorators, and flexible APIs.",
        [("Accept", "def log_call(*args, **kwargs):\n    print(args, kwargs)"),
         ("Forward", "def wrapper(*args, **kwargs):\n    return real(*args, **kwargs)"),
         ("Keyword-only", "def connect(host, *, timeout=30, retries=3):\n    ...   # timeout/retries must be passed by name")],
        ["A bare `*` in the signature forces the following params to be keyword-only.",
         "Unpacking at the call site (*seq, **dict) is the mirror image of collecting."],
        ["unpacking", "decorators"]),
    "decorators": _r(
        "Decorators",
        "Wrap functions to add behavior (timing, caching, retries, auth) without touching their bodies.",
        "A decorator is a callable that takes a function and returns a replacement. Use `functools.wraps` to preserve the original's identity. It is the idiomatic way to add cross-cutting behavior.",
        [("Define", "import functools\n\ndef timed(fn):\n    @functools.wraps(fn)\n    def inner(*a, **k):\n        import time; t = time.perf_counter()\n        try:\n            return fn(*a, **k)\n        finally:\n            print(fn.__name__, time.perf_counter() - t)\n    return inner"),
         ("Use", "@timed\ndef work():\n    ..."),
         ("Parameterized", "def retry(n):\n    def deco(fn):\n        @functools.wraps(fn)\n        def inner(*a, **k):\n            for _ in range(n):\n                try: return fn(*a, **k)\n                except Exception: pass\n            raise\n        return inner\n    return deco")],
        ["Always use functools.wraps or you lose the wrapped function's name and docstring.",
         "A parameterized decorator needs three nested layers — factory, decorator, wrapper."],
        ["star-args", "memoization"]),
    "memoization": _r(
        "Memoization with lru_cache",
        "Cache expensive pure-function results automatically with functools.lru_cache / cache.",
        "`@functools.lru_cache` memoizes results keyed by arguments, turning repeated or recursive calls into O(1) lookups. Use it for pure, hashable-argument functions.",
        [("Cache", "import functools\n\n@functools.lru_cache(maxsize=None)\ndef fib(n):\n    return n if n < 2 else fib(n-1) + fib(n-2)"),
         ("Unbounded", "@functools.cache   # 3.9+, == lru_cache(maxsize=None)\ndef load(path): ..."),
         ("Inspect / clear", "fib.cache_info()\nfib.cache_clear()")],
        ["Only decorate pure functions with hashable args; caching side-effecting functions hides bugs.",
         "An unbounded cache can grow forever — set maxsize for hot paths with many distinct keys."],
        ["decorators", "generators"]),
    "enumerate-zip": _r(
        "enumerate and zip",
        "Iterate with indices (enumerate) and over several sequences in lockstep (zip) instead of manual indexing.",
        "`enumerate` gives you index and value together; `zip` walks multiple iterables in parallel. Both replace error-prone `range(len(...))` indexing.",
        [("enumerate", "for i, item in enumerate(items, start=1):\n    print(i, item)"),
         ("zip", "for name, score in zip(names, scores):\n    print(name, score)"),
         ("zip to dict / unzip", "d = dict(zip(keys, values))\nxs, ys = zip(*points)")],
        ["zip stops at the shortest input; use itertools.zip_longest to pad instead.",
         "zip returns an iterator — wrap in list() if you need to reuse it."],
        ["comprehensions", "unpacking"]),
    "collections-toolkit": _r(
        "collections: defaultdict, Counter, deque",
        "Reach for specialized containers — defaultdict, Counter, deque — instead of reinventing them.",
        "The `collections` module ships containers that make common tasks trivial: grouping (defaultdict), tallying (Counter), and O(1) ends (deque).",
        [("defaultdict grouping", "from collections import defaultdict\ng = defaultdict(list)\nfor w in words:\n    g[w[0]].append(w)"),
         ("Counter", "from collections import Counter\nc = Counter(text.split())\nc.most_common(3)"),
         ("deque", "from collections import deque\nq = deque(maxlen=100)\nq.append(x); q.popleft()")],
        ["A deque with maxlen drops from the far end automatically — great for rolling windows.",
         "defaultdict creates missing keys on access; use dict.get if you don't want that."],
        ["python-collections", "comprehensions"]),
    "exception-handling": _r(
        "Exception handling",
        "Handle errors precisely with try/except/else/finally, catching narrow exception types.",
        "Catch the specific exceptions you can handle, keep the try body small, use `else` for the success path, and `finally` for cleanup. Broad excepts hide bugs.",
        [("Narrow", "try:\n    value = int(s)\nexcept ValueError:\n    value = 0"),
         ("else / finally", "try:\n    f = open(path)\nexcept OSError as e:\n    log(e); raise\nelse:\n    use(f)\nfinally:\n    f.close()"),
         ("Re-raise with context", "try:\n    parse()\nexcept ValueError as e:\n    raise ConfigError('bad config') from e")],
        ["Avoid bare `except:` — it catches KeyboardInterrupt and SystemExit too.",
         "Keep the try block to the single statement that can fail, so you don't mask unrelated errors."],
        ["custom-exceptions", "context-managers"]),
    "custom-exceptions": _r(
        "Custom exceptions",
        "Define your own exception hierarchy so callers can catch your errors specifically.",
        "Subclass `Exception` (not BaseException) to create meaningful, catchable error types. A small hierarchy lets callers handle categories of failure.",
        [("Define a hierarchy", "class AppError(Exception):\n    pass\n\nclass ConfigError(AppError):\n    pass\n\nclass NetworkError(AppError):\n    pass"),
         ("Raise with detail", "raise ConfigError(f'missing key: {key}')"),
         ("Catch a category", "try:\n    run()\nexcept AppError as e:\n    report(e)")],
        ["Inherit from Exception, never BaseException, for application errors.",
         "Carry structured data as attributes, not just a formatted string, when callers need it."],
        ["exception-handling"]),
    "pathlib-recipe": _r(
        "Filesystem paths with pathlib",
        "Manipulate paths and do file I/O with the object-oriented pathlib.Path instead of os.path string juggling.",
        "`pathlib.Path` treats paths as objects with methods — joining with `/`, reading/writing text, globbing, and existence checks — clearer and safer than string concatenation.",
        [("Build + read", "from pathlib import Path\np = Path.home() / 'data' / 'in.txt'\ntext = p.read_text(encoding='utf-8')"),
         ("Glob + iterate", "for f in Path('src').rglob('*.py'):\n    print(f, f.stat().st_size)"),
         ("Create + write", "out = Path('build/out.json')\nout.parent.mkdir(parents=True, exist_ok=True)\nout.write_text(data)")],
        ["Use `/` to join, never string '+' with os.sep.",
         "read_text/write_text handle open+close for you — pass encoding='utf-8' explicitly."],
        ["python-pathlib", "context-managers"]),
    "argparse-recipe": _r(
        "Command-line interfaces with argparse",
        "Build a real CLI — positional args, options, subcommands, help — with the standard argparse module.",
        "`argparse` turns a function into a proper command-line tool with `--help`, type conversion, defaults, and subcommands. It is the standard, dependency-free way to accept arguments.",
        [("Basic", "import argparse\np = argparse.ArgumentParser(description='do a thing')\np.add_argument('path')\np.add_argument('-n', '--num', type=int, default=1)\np.add_argument('-v', '--verbose', action='store_true')\nargs = p.parse_args()"),
         ("Subcommands", "sub = p.add_subparsers(dest='cmd')\nb = sub.add_parser('build'); b.add_argument('target')")],
        ["Give every option a sensible default and a help string.",
         "Use type= for conversion and validation instead of parsing strings yourself."],
        ["python-argparse", "star-args"]),
    "logging-recipe": _r(
        "Logging done right",
        "Emit structured, level-based diagnostics with the logging module instead of print.",
        "`logging` gives you levels (DEBUG..CRITICAL), configurable handlers, and per-module loggers. Use a module-level logger and configure once at the entry point.",
        [("Set up", "import logging\nlogging.basicConfig(level=logging.INFO,\n    format='%(asctime)s %(levelname)s %(name)s: %(message)s')\nlog = logging.getLogger(__name__)"),
         ("Use", "log.info('processing %s', path)\nlog.warning('retrying (%d/%d)', i, n)\nlog.exception('failed')   # inside an except: adds traceback")],
        ["Pass args to the logger (log.info('x=%s', x)) — don't f-string, so formatting is lazy.",
         "Configure logging once at the program's entry point, not in library modules."],
        ["python-logging", "exception-handling"]),
    "json-io": _r(
        "Reading and writing JSON",
        "Serialize and parse JSON with the json module, including files and pretty-printing.",
        "`json` converts between Python objects and JSON text. Use `dump`/`load` for files and `dumps`/`loads` for strings; set `indent` for human-readable output.",
        [("String", "import json\nobj = json.loads('{\"a\": 1}')\ntext = json.dumps(obj, indent=2)"),
         ("File", "with open('data.json') as f:\n    data = json.load(f)\nwith open('out.json', 'w') as f:\n    json.dump(data, f, indent=2, ensure_ascii=False)")],
        ["Set ensure_ascii=False to keep non-ASCII readable.",
         "JSON keys are always strings; integer dict keys become strings on round-trip."],
        ["python-json", "pathlib-recipe"]),
    "csv-io": _r(
        "Reading and writing CSV",
        "Parse and emit delimited data safely with the csv module, including headers via DictReader.",
        "`csv` handles quoting, delimiters, and newlines correctly — do not split on commas yourself. `DictReader`/`DictWriter` map rows to dicts by header.",
        [("Read", "import csv\nwith open('data.csv', newline='') as f:\n    for row in csv.DictReader(f):\n        print(row['name'], row['age'])"),
         ("Write", "with open('out.csv', 'w', newline='') as f:\n    w = csv.DictWriter(f, fieldnames=['name', 'age'])\n    w.writeheader(); w.writerow({'name': 'Ada', 'age': 36})")],
        ["Always open CSV files with newline='' to avoid blank rows on Windows.",
         "Never parse CSV by str.split(',') — quoted fields with commas will break it."],
        ["python-csv", "json-io"]),
    "regex-recipe": _r(
        "Regular expressions in Python",
        "Match, extract, and replace text with the re module — compiled patterns, groups, and substitution.",
        "`re` provides regular expressions. Compile hot patterns once, use raw strings, name your groups, and prefer `search`/`finditer` for scanning.",
        [("Search + groups", "import re\nm = re.search(r'(?P<user>\\w+)@(?P<host>[\\w.]+)', s)\nif m:\n    print(m.group('user'), m.group('host'))"),
         ("Find all / iterate", "for m in re.finditer(r'\\d+', text):\n    print(m.group())"),
         ("Substitute", "clean = re.sub(r'\\s+', ' ', messy).strip()")],
        ["Use raw strings (r'...') so backslashes reach the regex engine intact.",
         "Compile with re.compile when reusing a pattern in a loop."],
        ["python-re", "f-strings"]),
    "datetime-recipe": _r(
        "Dates and times",
        "Work with timestamps, durations, and formatting using datetime, timezone, and timedelta.",
        "`datetime` handles points in time and `timedelta` handles durations. Prefer timezone-aware UTC for storage and convert for display.",
        [("Now / UTC", "from datetime import datetime, timezone, timedelta\nnow = datetime.now(timezone.utc)"),
         ("Arithmetic", "yesterday = now - timedelta(days=1)"),
         ("Parse / format", "d = datetime.strptime('2026-07-25', '%Y-%m-%d')\ns = now.strftime('%Y-%m-%dT%H:%M:%SZ')"),
         ("ISO", "d = datetime.fromisoformat('2026-07-25T12:00:00+00:00')")],
        ["Prefer timezone-aware datetimes (attach tz) — naive datetimes cause silent bugs.",
         "Store/transport in UTC; convert to local only for display."],
        ["python-datetime"]),
    "typing-hints": _r(
        "Type hints",
        "Annotate functions and variables with types so tools and readers catch mistakes early.",
        "Type hints document intent and enable static checkers (mypy, pyright) and editor help. They do not affect runtime behavior but massively improve maintainability.",
        [("Functions", "def greet(name: str, times: int = 1) -> str:\n    return (f'hi {name} ' * times).strip()"),
         ("Collections + optional", "from typing import Optional\ndef find(xs: list[int], target: int) -> Optional[int]:\n    return xs.index(target) if target in xs else None"),
         ("Aliases", "Vector = list[float]\ndef scale(v: Vector, k: float) -> Vector:\n    return [x * k for x in v]")],
        ["Hints are not enforced at runtime — run a checker (mypy/pyright) to get value.",
         "Use built-in generics (list[int], dict[str, int]) on modern Python instead of typing.List."],
        ["dataclasses", "protocols"]),
    "match-statement": _r(
        "Structural pattern matching (match)",
        "Branch on the shape of data with match/case, destructuring as you go (Python 3.10+).",
        "`match` compares a value against structural patterns and binds parts of it — cleaner than long if/elif chains for tagged data, sequences, and mappings.",
        [("Literals + capture", "match command.split():\n    case ['go', direction]:\n        move(direction)\n    case ['quit']:\n        raise SystemExit\n    case _:\n        print('unknown')"),
         ("Mappings / classes", "match event:\n    case {'type': 'click', 'x': x, 'y': y}:\n        click(x, y)\n    case Point(x=0, y=0):\n        origin()")],
        ["`case _` is the wildcard/default — put it last.",
         "A bare name in a pattern binds (captures), it does not compare; use dotted names or guards to compare."],
        ["enum", "unpacking"]),
    "async-await": _r(
        "async / await with asyncio",
        "Run many I/O-bound operations concurrently with coroutines instead of threads.",
        "`async def` defines a coroutine; `await` yields control while I/O is pending. asyncio schedules thousands of concurrent I/O operations on one thread.",
        [("Coroutine + run", "import asyncio\n\nasync def fetch(n):\n    await asyncio.sleep(0.1)\n    return n * 2\n\nasyncio.run(fetch(21))"),
         ("Concurrent gather", "async def main():\n    results = await asyncio.gather(*(fetch(i) for i in range(10)))\n    return results\nasyncio.run(main())")],
        ["await only inside async functions; call asyncio.run() once at the top level.",
         "asyncio helps I/O-bound work, not CPU-bound — use multiprocessing for CPU."],
        ["python-asyncio", "generators"]),
    "subprocess-recipe": _r(
        "Running external commands",
        "Invoke other programs safely from Python with subprocess.run, capturing output and checking status.",
        "`subprocess.run` is the modern entry point: pass a list of arguments (no shell), capture output, and check the return code. Avoid shell=True with untrusted input.",
        [("Capture + check", "import subprocess\nr = subprocess.run(['git', 'rev-parse', 'HEAD'],\n    capture_output=True, text=True, check=True)\nprint(r.stdout.strip())"),
         ("Handle failure", "try:\n    subprocess.run(['make'], check=True)\nexcept subprocess.CalledProcessError as e:\n    print('build failed', e.returncode)")],
        ["Pass args as a list, not a string, and avoid shell=True to prevent injection.",
         "Use text=True to get str instead of bytes; set timeout= to avoid hangs."],
        ["python-subprocess", "exception-handling"]),
    "iterators": _r(
        "The iterator protocol",
        "Make your own objects iterable by implementing __iter__/__next__, and consume iterators lazily.",
        "An iterable returns an iterator from `__iter__`; an iterator produces values via `__next__` and raises StopIteration when done. Understanding it demystifies for-loops and generators.",
        [("Custom iterator", "class Count:\n    def __init__(self, stop):\n        self.i, self.stop = 0, stop\n    def __iter__(self):\n        return self\n    def __next__(self):\n        if self.i >= self.stop:\n            raise StopIteration\n        self.i += 1\n        return self.i - 1"),
         ("Consume", "it = iter([1, 2, 3])\nnext(it)          # 1\nnext(it, None)    # default avoids StopIteration")],
        ["Prefer a generator function over a hand-written iterator class when you can.",
         "next(it, default) is the safe way to pull one value without catching StopIteration."],
        ["generators", "python-itertools"]),
    "property-descriptors": _r(
        "Properties and computed attributes",
        "Expose computed or validated attributes with @property instead of getter/setter methods.",
        "`@property` turns a method into an attribute access, letting you compute or validate on get/set while keeping a clean attribute interface.",
        [("Computed", "class Circle:\n    def __init__(self, r): self.r = r\n    @property\n    def area(self):\n        return 3.14159 * self.r ** 2"),
         ("Validated setter", "class Temp:\n    def __init__(self): self._c = 0\n    @property\n    def c(self): return self._c\n    @c.setter\n    def c(self, v):\n        if v < -273.15: raise ValueError('too cold')\n        self._c = v")],
        ["Don't hide expensive work behind a property that looks like a cheap attribute.",
         "Back a settable property with a private attribute (self._x) to avoid infinite recursion."],
        ["dataclasses", "class-methods"]),
    "class-methods": _r(
        "classmethod and staticmethod",
        "Use @classmethod for alternative constructors and @staticmethod for namespaced helpers.",
        "`@classmethod` receives the class (great for factory constructors); `@staticmethod` receives nothing (a plain function living in the class namespace).",
        [("Alternative constructor", "class Date:\n    def __init__(self, y, m, d): self.y, self.m, self.d = y, m, d\n    @classmethod\n    def from_iso(cls, s):\n        return cls(*map(int, s.split('-')))"),
         ("Static helper", "class MathUtil:\n    @staticmethod\n    def clamp(x, lo, hi):\n        return max(lo, min(hi, x))")],
        ["Use classmethod (cls) for factories so subclasses build the right type.",
         "If a method uses neither self nor cls, make it a staticmethod (or a module function)."],
        ["property-descriptors", "dataclasses"]),
    "dunder-methods": _r(
        "Dunder (magic) methods",
        "Make objects behave like built-ins by implementing __repr__, __eq__, __len__, __getitem__, and friends.",
        "Special 'dunder' methods hook your class into language operators and protocols — printing, equality, length, indexing, iteration, and arithmetic.",
        [("Repr + eq", "class Money:\n    def __init__(self, c): self.c = c\n    def __repr__(self): return f'Money({self.c})'\n    def __eq__(self, o): return isinstance(o, Money) and o.c == self.c\n    def __hash__(self): return hash(self.c)"),
         ("Container protocol", "class Deck:\n    def __init__(self, cards): self._c = cards\n    def __len__(self): return len(self._c)\n    def __getitem__(self, i): return self._c[i]")],
        ["If you define __eq__, define __hash__ too (or set it to None for unhashable).",
         "Implement __repr__ for every class — it makes debugging and logs far clearer."],
        ["dataclasses", "iterators"]),
    "sorting-key": _r(
        "Sorting with keys",
        "Sort and find extremes by a computed key with sorted, min, max, and operator helpers.",
        "The `key=` argument computes a sort value per element without mutating it. Combine with `reverse=`, `operator.itemgetter`, and tuples for multi-level sorts.",
        [("By attribute/field", "people.sort(key=lambda p: p.age)\nrows = sorted(rows, key=lambda r: (r['dept'], -r['salary']))"),
         ("operator helpers", "from operator import itemgetter, attrgetter\nsorted(pairs, key=itemgetter(1))\nsorted(objs, key=attrgetter('name'))"),
         ("Extremes", "oldest = max(people, key=lambda p: p.age)")],
        ["Return a tuple from key= for multi-level sorts; negate a numeric field to reverse just that level.",
         "sorted() returns a new list; list.sort() sorts in place and returns None."],
        ["comprehensions", "collections-toolkit"]),
    "string-methods": _r(
        "String manipulation",
        "Split, join, strip, replace, and test strings with their built-in methods instead of manual loops.",
        "`str` methods cover most text work: `split`/`join` for tokenizing, `strip` for trimming, `startswith`/`endswith` for tests, `replace` and `translate` for edits.",
        [("Split / join", "parts = line.split(',')\ncsv = ','.join(fields)"),
         ("Trim / case", "clean = raw.strip().lower()\ntitle = name.title()"),
         ("Test / find", "if path.endswith('.py'): ...\nif 'error' in log_line.lower(): ...")],
        ["Strings are immutable — every method returns a new string; assign the result.",
         "Build big strings with ''.join(list) in a loop, not repeated += concatenation."],
        ["f-strings", "regex-recipe"]),
    "slicing": _r(
        "Sequence slicing",
        "Extract, reverse, and step through parts of sequences with slice notation [start:stop:step].",
        "Slicing produces a subsequence with `seq[start:stop:step]`. Omitted bounds default to the ends; a negative step reverses.",
        [("Basics", "xs[1:4]     # items 1,2,3\nxs[:3]      # first three\nxs[-2:]     # last two"),
         ("Step / reverse", "xs[::2]     # every other\nxs[::-1]    # reversed\ns = text[::-1]"),
         ("Assign to a slice", "xs[1:3] = [10, 20, 30]   # lists only")],
        ["Slicing a list copies (shallow); slicing a string/tuple makes a new one.",
         "Out-of-range slice bounds are clamped, not errors — unlike single-index access."],
        ["unpacking", "string-methods"]),
    "walrus": _r(
        "Assignment expressions (walrus :=)",
        "Assign and use a value in the same expression with := to avoid recomputation or extra lines.",
        "The walrus operator `:=` binds a name as part of an expression — handy in while-conditions, comprehension filters, and to avoid calling something twice.",
        [("While read", "while (chunk := f.read(8192)):\n    process(chunk)"),
         ("Filter + reuse", "results = [y for x in data if (y := f(x)) is not None]"),
         ("Avoid double call", "if (n := len(items)) > 10:\n    print(f'{n} is a lot')")],
        ["Wrap the walrus in parentheses where precedence is ambiguous.",
         "Use it to remove repetition, not to cram unrelated logic into one line."],
        ["generators", "comprehensions"]),
    "virtualenv-recipe": _r(
        "Virtual environments",
        "Isolate a project's dependencies in a virtual environment so installs don't collide globally.",
        "A venv is a self-contained Python with its own site-packages. Create one per project so dependencies are reproducible and isolated.",
        [("Create + activate", "python -m venv .venv\nsource .venv/bin/activate        # Windows: .venv\\Scripts\\activate"),
         ("Install + freeze", "pip install requests\npip freeze > requirements.txt"),
         ("Recreate elsewhere", "python -m venv .venv && source .venv/bin/activate\npip install -r requirements.txt")],
        ["Never commit the .venv directory; commit requirements.txt instead.",
         "Activate the venv (or use its python directly) before pip install, or you pollute the global env."],
        ["argparse-recipe", "subprocess-recipe"]),
    "main-guard": _r(
        "The `if __name__ == '__main__'` guard",
        "Separate a module's importable definitions from its script entry point with the main-guard.",
        "Code under `if __name__ == '__main__':` runs only when the file is executed directly, not when imported. It lets one file be both a reusable library and a runnable script.",
        [("Pattern", "def main() -> int:\n    ...\n    return 0\n\nif __name__ == '__main__':\n    import sys\n    sys.exit(main())")],
        ["Keep top-level code minimal; put logic in functions so importing the module has no side effects.",
         "Return an int from main() and pass it to sys.exit() to set the process exit code."],
        ["argparse-recipe", "subprocess-recipe"]),
    "dict-get-setdefault": _r(
        "dict.get and setdefault",
        "Read possibly-missing keys with get(), and initialize-then-append with setdefault().",
        "`dict.get(key, default)` avoids KeyError; `dict.setdefault(key, default)` returns the existing value or inserts and returns a default — a one-liner for grouping without defaultdict.",
        [("Safe read", "count = counts.get(word, 0)\nconfig.get('timeout', 30)"),
         ("Group", "groups = {}\nfor w in words:\n    groups.setdefault(w[0], []).append(w)")],
        ["setdefault always evaluates its default argument — for expensive defaults prefer defaultdict.",
         "get() returns None by default; pass an explicit default when None is a valid value."],
        ["collections-toolkit", "comprehensions"]),
    "sets-operations": _r(
        "Set operations",
        "Deduplicate and compute unions, intersections, and differences with set operators.",
        "Sets store unique, unordered, hashable items and support fast membership and algebra: `|` union, `&` intersection, `-` difference, `^` symmetric difference.",
        [("Dedup + membership", "unique = set(items)\nif x in unique: ..."),
         ("Algebra", "common = a & b\nonly_a = a - b\neither = a | b")],
        ["Sets are unordered — do not rely on iteration order.",
         "Elements must be hashable; use frozenset for a set you can put inside another set."],
        ["collections-toolkit", "comprehensions"]),
    "ternary-truthiness": _r(
        "Conditional expressions and truthiness",
        "Choose values inline with the ternary, and lean on Python's truthiness rules cleanly.",
        "`a if cond else b` selects a value in an expression. Empty containers, 0, '', and None are falsy — exploit this for concise, readable defaults.",
        [("Ternary", "label = 'even' if n % 2 == 0 else 'odd'"),
         ("Truthy defaults", "name = user_input or 'anonymous'\nif not items:\n    return 'empty'")],
        ["`or` returns the first truthy operand, not a bool — great for defaults, surprising if you expected True/False.",
         "Compare to None with `is None`, not truthiness, when 0/'' are valid values."],
        ["walrus", "match-statement"]),
    "closures": _r(
        "Closures and nonlocal",
        "Capture enclosing-scope variables in nested functions, and mutate them with nonlocal.",
        "A closure is a nested function that remembers variables from the scope where it was defined. `nonlocal` lets it rebind those variables; without it, assignment creates a new local.",
        [("Capture", "def multiplier(k):\n    def mul(x):\n        return x * k\n    return mul\ntriple = multiplier(3)"),
         ("nonlocal counter", "def make_counter():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 1\n        return n\n    return inc")],
        ["Late binding: closures capture the variable, not its value — loop-created closures all see the final value unless you bind it (e.g. default arg).",
         "Use nonlocal to rebind an enclosing variable; without it, assignment shadows it locally."],
        ["decorators", "class-methods"]),
    "copy-semantics": _r(
        "Copying: references, shallow, and deep",
        "Understand that assignment shares references, and copy explicitly with slicing, copy(), or deepcopy().",
        "Assignment binds another name to the same object; mutating through one name is visible through the other. Copy explicitly when you need independence.",
        [("Shared vs copied", "a = [1, 2]; b = a          # same list\nc = a[:]                    # shallow copy\nimport copy\nd = copy.deepcopy(nested)   # fully independent"),
         ("Gotcha", "grid = [[0] * 3] * 3        # WRONG: three refs to one row\ngrid = [[0] * 3 for _ in range(3)]  # right")],
        ["`[[0]*3]*3` makes three references to the same inner list — a classic bug. Use a comprehension.",
         "Shallow copy duplicates the outer container only; nested objects are still shared."],
        ["slicing", "dataclasses"]),
    "tempfile-recipe": _r(
        "Temporary files and directories",
        "Create secure, auto-cleaned temporary files and directories with the tempfile module.",
        "`tempfile` makes uniquely named temp files/dirs in the right location, and its context managers remove them automatically — safer than hand-rolled /tmp paths.",
        [("Temp dir", "import tempfile, pathlib\nwith tempfile.TemporaryDirectory() as d:\n    p = pathlib.Path(d) / 'work.txt'\n    p.write_text('scratch')\n# directory removed here"),
         ("Named temp file", "with tempfile.NamedTemporaryFile('w', suffix='.json', delete=False) as f:\n    f.write(data)\n    path = f.name")],
        ["Prefer the context managers so cleanup is automatic even on error.",
         "Never build temp paths by hand in /tmp — race conditions and collisions."],
        ["pathlib-recipe", "context-managers"]),
    "hashlib-recipe": _r(
        "Hashing with hashlib",
        "Compute cryptographic and content hashes of bytes and files with hashlib.",
        "`hashlib` provides SHA-256 and friends for integrity checks, content addressing, and dedup. Hash bytes, and stream large files in chunks.",
        [("Hash bytes/text", "import hashlib\nh = hashlib.sha256(b'hello').hexdigest()\nhashlib.sha256(text.encode()).hexdigest()"),
         ("Stream a file", "h = hashlib.sha256()\nwith open(path, 'rb') as f:\n    for chunk in iter(lambda: f.read(8192), b''):\n        h.update(chunk)\nprint(h.hexdigest())")],
        ["Hash bytes, not str — encode text first with a fixed encoding.",
         "Do not use MD5/SHA-1 for security; they are fine only for non-adversarial checksums."],
        ["json-io", "pathlib-recipe"]),
    "uuid-recipe": _r(
        "Generating unique IDs with uuid",
        "Create globally unique identifiers with the uuid module for records, files, and correlation.",
        "`uuid.uuid4()` returns a random 128-bit identifier with negligible collision risk — the go-to for IDs you generate without a central authority.",
        [("Random ID", "import uuid\nid = uuid.uuid4()\nid_str = str(uuid.uuid4())          # '3f2504e0-...'\nid_hex = uuid.uuid4().hex           # no dashes"),
         ("Deterministic (namespaced)", "uuid.uuid5(uuid.NAMESPACE_URL, 'https://x/y')")],
        ["Use uuid4 for random IDs; uuid1 embeds the MAC/time and can leak host info.",
         "Store as a string or the native 16 bytes consistently; don't mix representations."],
        ["hashlib-recipe", "datetime-recipe"]),
    "partial-functions": _r(
        "Partial application with functools.partial",
        "Pre-bind some arguments of a function to make a simpler, specialized callable.",
        "`functools.partial` freezes some arguments, returning a new callable that needs only the rest — cleaner than a lambda for adapting callbacks and configuring functions.",
        [("Specialize", "from functools import partial\nint2 = partial(int, base=2)\nint2('1010')                 # 10"),
         ("Adapt a callback", "handler = partial(save, directory='/out')\nfor item in items:\n    handler(item)")],
        ["partial is picklable and introspectable; a lambda is often neither.",
         "Bind keyword args by name to avoid ambiguity with the remaining positional args."],
        ["decorators", "sorting-key"]),
    "heapq-bisect": _r(
        "Priority queues and sorted insertion (heapq, bisect)",
        "Keep the smallest items handy with heapq, and insert into sorted lists with bisect.",
        "`heapq` maintains a min-heap in a list for O(log n) push/pop of the smallest item; `bisect` finds insertion points to keep a list sorted without a full re-sort.",
        [("Heap / top-k", "import heapq\nheapq.nlargest(3, data)\nh = []\nheapq.heappush(h, 5); smallest = heapq.heappop(h)"),
         ("Bisect insert", "import bisect\nbisect.insort(sorted_list, value)\ni = bisect.bisect_left(sorted_list, target)")],
        ["heapq is a min-heap; negate values (or use tuples) for a max-heap.",
         "bisect assumes the list is already sorted — it does not check."],
        ["sorting-key", "collections-toolkit"]),
    "global-vs-local": _r(
        "Scope: local, global, and the LEGB rule",
        "Know where names resolve (Local, Enclosing, Global, Built-in) and avoid the global statement.",
        "Python resolves names by the LEGB rule. Assignment inside a function creates a local unless declared `global`/`nonlocal`. Prefer passing and returning values over mutating globals.",
        [("Read vs assign", "x = 10\ndef show(): print(x)      # reads global fine\ndef bad():\n    x = x + 1              # UnboundLocalError: x is local here"),
         ("Explicit global (avoid)", "def set_flag():\n    global FLAG\n    FLAG = True")],
        ["Assigning to a name anywhere in a function makes it local throughout — read-before-assign then fails.",
         "Global mutable state is hard to test; pass arguments and return results instead."],
        ["closures", "main-guard"]),
    "assertions": _r(
        "Assertions and invariants",
        "State internal invariants with assert during development — but never for user input validation.",
        "`assert cond, msg` documents and checks an assumption. It is a debugging aid for programmer errors, and can be stripped with `python -O`, so it must not guard real logic.",
        [("Invariant", "def average(xs):\n    assert xs, 'average of empty sequence'\n    return sum(xs) / len(xs)")],
        ["Never use assert to validate untrusted input or enforce security — `-O` removes it.",
         "Assert conditions that should be impossible if the code is correct, not conditions that can legitimately occur."],
        ["custom-exceptions", "exception-handling"]),
    "chained-comparison": _r(
        "Chained comparisons",
        "Write range and multi-way comparisons the mathematical way: lo <= x < hi.",
        "Python evaluates `a < b < c` as `a < b and b < c`, each operand once. It reads like math and prevents off-by-one mistakes in bounds checks.",
        [("Range check", "if 0 <= i < len(xs):\n    return xs[i]"),
         ("Equality chain", "if a == b == c:\n    ...")],
        ["Each middle operand is evaluated once; avoid side effects there anyway.",
         "Don't over-chain — three comparisons is usually the readable limit."],
        ["ternary-truthiness", "slicing"]),
    "shutil-recipe": _r(
        "High-level file operations with shutil",
        "Copy trees, move, and remove directories, and find executables with the shutil module.",
        "`shutil` provides the high-level file operations `os` lacks: recursive copy/remove, move across filesystems, archive make/unpack, and `which`.",
        [("Copy / move / remove tree", "import shutil\nshutil.copy2('a', 'b')          # copy with metadata\nshutil.copytree('src', 'dst')\nshutil.move('a', 'archive/')\nshutil.rmtree('build')"),
         ("Find a program", "path = shutil.which('git')")],
        ["rmtree is recursive and irreversible — double-check the target.",
         "copytree fails if the destination exists (unless dirs_exist_ok=True)."],
        ["pathlib-recipe", "subprocess-recipe"]),
    "os-environ": _r(
        "Environment variables and sys.argv",
        "Read configuration from the environment and command-line arguments the standard way.",
        "`os.environ` is a dict of environment variables; `sys.argv` is the list of command-line arguments. Read config from the environment for 12-factor style apps, with sensible defaults.",
        [("Env with default", "import os\nport = int(os.environ.get('PORT', '8080'))\ntoken = os.environ['API_TOKEN']       # required: KeyError if unset"),
         ("Args", "import sys\nscript, *args = sys.argv")],
        ["os.environ values are always strings — convert types explicitly.",
         "For anything beyond a couple of flags, use argparse instead of parsing sys.argv by hand."],
        ["argparse-recipe", "main-guard"]),
    "abc-protocols": _r(
        "Abstract base classes and Protocols",
        "Define interfaces with abc.ABC (nominal) or typing.Protocol (structural, duck-typed).",
        "An ABC declares methods subclasses must implement; a Protocol describes a shape any object can satisfy without inheritance. Use ABCs for your own hierarchies, Protocols to type duck-typed inputs.",
        [("ABC", "from abc import ABC, abstractmethod\nclass Store(ABC):\n    @abstractmethod\n    def get(self, k): ...\n    @abstractmethod\n    def put(self, k, v): ..."),
         ("Protocol", "from typing import Protocol\nclass Reader(Protocol):\n    def read(self, n: int) -> bytes: ...")],
        ["An ABC with an unimplemented abstractmethod cannot be instantiated — that's the point.",
         "Protocols are checked structurally by type checkers; no explicit subclassing needed."],
        ["typing-hints", "dunder-methods"]),
    "chainmap-namedtuple": _r(
        "namedtuple and ChainMap",
        "Make lightweight immutable records (namedtuple) and layered lookups (ChainMap).",
        "`collections.namedtuple` gives tuples named fields (immutable, memory-light); `ChainMap` searches several dicts in order — perfect for layered config (CLI over env over defaults).",
        [("namedtuple", "from collections import namedtuple\nPoint = namedtuple('Point', 'x y')\np = Point(1, 2); p.x"),
         ("ChainMap", "from collections import ChainMap\ncfg = ChainMap(cli_opts, env_opts, defaults)\ncfg['timeout']       # first map that has it wins")],
        ["Prefer a dataclass over namedtuple when you need defaults, methods, or mutability.",
         "ChainMap writes go to the first mapping only — reads search all of them."],
        ["dataclasses", "collections-toolkit"]),
    "random-recipe": _r(
        "Randomness with the random module",
        "Generate random numbers, choices, and shuffles — and know when you need secrets instead.",
        "`random` covers simulations and sampling: `randint`, `choice`, `sample`, `shuffle`, `random`. For tokens and passwords, use `secrets`, which is cryptographically secure.",
        [("Common draws", "import random\nrandom.randint(1, 6)\nrandom.choice(items)\nrandom.sample(pool, 3)\nrandom.shuffle(deck)"),
         ("Secure tokens", "import secrets\nsecrets.token_hex(16)\nsecrets.choice(items)")],
        ["Never use random for passwords, tokens, or keys — use secrets.",
         "Seed random only for reproducible tests; never seed a security-sensitive generator."],
        ["hashlib-recipe", "uuid-recipe"]),
    "string-io": _r(
        "In-memory text and bytes buffers (io)",
        "Treat strings and bytes as file-like objects with io.StringIO / io.BytesIO.",
        "`io.StringIO`/`io.BytesIO` present an in-memory buffer with the file API, so you can feed string data to code that expects a file, or capture output without touching disk.",
        [("Build text like a file", "import io, csv\nbuf = io.StringIO()\ncsv.writer(buf).writerow(['a', 'b'])\ntext = buf.getvalue()"),
         ("Feed a parser", "import io\nparse(io.StringIO(some_text))")],
        ["Call getvalue() to retrieve the contents; the buffer's position matters if you also read it.",
         "Use BytesIO for binary formats (images, gzip), StringIO for text."],
        ["csv-io", "context-managers"]),
    "map-filter": _r(
        "map, filter, and functional transforms",
        "Transform and select items functionally with map/filter, favouring comprehensions where clearer.",
        "`map(f, it)` and `filter(pred, it)` return lazy iterators. Comprehensions usually read better, but map/filter shine when you already have a named function to apply.",
        [("map / filter", "lengths = list(map(len, words))\npositives = list(filter(lambda n: n > 0, nums))"),
         ("With a named fn", "cleaned = map(str.strip, lines)")],
        ["Both return lazy iterators — wrap in list() to materialize or reuse.",
         "For an inline expression, a comprehension is usually clearer than map/filter with a lambda."],
        ["comprehensions", "partial-functions"]),
    "reduce-accumulate": _r(
        "Folding with reduce and accumulate",
        "Collapse an iterable to one value (reduce) or a running series (itertools.accumulate).",
        "`functools.reduce` folds a binary function across items to a single result; `itertools.accumulate` yields the running results. Reach for them for products, running totals, and custom folds.",
        [("reduce", "from functools import reduce\nproduct = reduce(lambda a, b: a * b, nums, 1)"),
         ("accumulate", "from itertools import accumulate\nrunning = list(accumulate(nums))          # running sum\nrunning_max = list(accumulate(nums, max))")],
        ["Prefer sum()/min()/max()/math.prod() over reduce when one exists — clearer and faster.",
         "Always give reduce an explicit initializer to handle empty iterables safely."],
        ["collections-toolkit", "map-filter"]),
    "zip-longest-groupby": _r(
        "itertools: zip_longest, groupby, chain",
        "Combine and group iterables with itertools' zip_longest, groupby, and chain.",
        "`itertools` composes iterators efficiently: `chain` concatenates, `zip_longest` pads uneven inputs, and `groupby` clusters consecutive equal keys (sort first for global grouping).",
        [("chain / zip_longest", "from itertools import chain, zip_longest\nall_items = list(chain(a, b, c))\npairs = list(zip_longest(x, y, fillvalue=0))"),
         ("groupby (sorted!)", "from itertools import groupby\ndata.sort(key=lambda r: r.dept)\nfor dept, rows in groupby(data, key=lambda r: r.dept):\n    print(dept, len(list(rows)))")],
        ["groupby groups only *consecutive* equal keys — sort by the same key first.",
         "The groups from groupby are one-shot iterators; consume each before advancing."],
        ["python-itertools", "sorting-key"]),
    "format-numbers": _r(
        "Formatting and rounding numbers",
        "Present numbers precisely with format specs, and round correctly with round/Decimal.",
        "Use the format mini-language for display (width, precision, separators, percent) and `decimal.Decimal` when exactness matters (money) — floats are binary approximations.",
        [("Display", "f'{1234567:,}'          # 1,234,567\nf'{0.1234:.1%}'         # 12.3%\nf'{3.14159:8.2f}'       # '    3.14'"),
         ("Exact money", "from decimal import Decimal\nprice = Decimal('19.99') * 3")],
        ["Never store money as float; use Decimal or integer cents.",
         "round() uses banker's rounding (round-half-to-even) — expected for stats, surprising for currency."],
        ["f-strings", "datetime-recipe"]),
    "with-suppress": _r(
        "contextlib helpers: suppress, closing, redirect",
        "Silence expected exceptions and adapt resources with contextlib's small context managers.",
        "`contextlib.suppress` swallows named exceptions cleanly; `closing` adapts objects with only a close(); `redirect_stdout` captures prints. They replace boilerplate try/except/finally.",
        [("suppress", "from contextlib import suppress\nwith suppress(FileNotFoundError):\n    os.remove(path)"),
         ("redirect", "import io, contextlib\nbuf = io.StringIO()\nwith contextlib.redirect_stdout(buf):\n    noisy()\ncaptured = buf.getvalue()")],
        ["Only suppress exceptions you truly expect and intend to ignore — never blanket-suppress Exception.",
         "suppress is for 'best effort' cleanup, not for control flow."],
        ["context-managers", "exception-handling"]),
    "pickle-warning": _r(
        "Serialization: pickle vs json (and when not to)",
        "Persist Python objects with pickle for trusted data, and prefer json for anything crossing a trust boundary.",
        "`pickle` serializes almost any Python object but executes code on load — never unpickle untrusted data. Use JSON for interchange and untrusted input; use pickle only for your own local caches.",
        [("Pickle (trusted only)", "import pickle\nwith open('cache.pkl', 'wb') as f:\n    pickle.dump(obj, f)\nwith open('cache.pkl', 'rb') as f:\n    obj = pickle.load(f)   # only on data YOU wrote")],
        ["Unpickling untrusted data can execute arbitrary code — a remote-code-execution risk. Use JSON instead.",
         "Pickle format is Python- and version-specific; don't use it as a long-term or cross-language format."],
        ["json-io", "hashlib-recipe"]),
    "text-encoding": _r(
        "Text encoding and bytes",
        "Convert between str and bytes explicitly with encode/decode, always naming the encoding.",
        "`str` is Unicode text; `bytes` is raw octets. Convert at the boundaries with `.encode()`/`.decode()` and always specify `utf-8` — never rely on the platform default.",
        [("Encode / decode", "data = text.encode('utf-8')\ntext = data.decode('utf-8')"),
         ("Robust decode", "text = data.decode('utf-8', errors='replace')"),
         ("File I/O", "open('f.txt', encoding='utf-8')")],
        ["Always pass encoding='utf-8' to open() — the default varies by OS and burns you on Windows.",
         "Hash, network, and file bytes are bytes; convert to str only when you need text operations."],
        ["string-methods", "hashlib-recipe"]),
    "default-args": _r(
        "Default arguments (and the mutable-default trap)",
        "Give parameters sensible defaults, and never use a mutable object as a default value.",
        "Default argument values are evaluated once, at definition time. A mutable default (list/dict) is shared across all calls — a notorious bug. Use None and create inside.",
        [("Wrong vs right", "def add(x, bucket=[]):        # BUG: shared list\n    bucket.append(x); return bucket\n\ndef add(x, bucket=None):      # correct\n    if bucket is None:\n        bucket = []\n    bucket.append(x); return bucket")],
        ["A mutable default is created once and reused across calls — use None as the sentinel.",
         "Keyword defaults document intent; keep them immutable (numbers, strings, tuples, None)."],
        ["star-args", "dict-get-setdefault"]),
    "logging-vs-print": _r(
        "Choosing output: print, logging, and stderr",
        "Send results to stdout, diagnostics to logging/stderr, and never mix the two streams.",
        "A well-behaved program prints its *data* to stdout so pipelines can consume it, and its *diagnostics* (progress, warnings, errors) to stderr or the logging module. Mixing them corrupts downstream parsing.",
        [("Separate streams", "import sys\nprint(result)                          # data -> stdout\nprint('processing...', file=sys.stderr) # status -> stderr"),
         ("Prefer logging for apps", "import logging\nlog = logging.getLogger(__name__)\nlog.info('done')")],
        ["Emitting logs to stdout breaks tools that parse your output — use stderr or logging.",
         "print is fine for CLI results and quick scripts; use logging for anything long-lived."],
        ["logging-recipe", "os-environ"]),
}
